### ISSUE TITLE
Get error after add spring-boot-starter-web in mybatis-spring-boot-starter-sample-annotation

### ISSUE THREAD

**Issue by QiuMing** [mybatis/spring-boot-starter#121]
Hello ,I am learning mybatis-spring-boot-starter.And I just add spring-boot-starter-web in the pom.And  then start it ,get this error
```
### Error querying database.  Cause: org.h2.jdbc.JdbcSQLException: Table "CITY" not found; SQL statement:
select * from city where state = ? [42102-193]
### The error may exist in sample/mybatis/mapper/CityMapper.java (best guess)
### The error may involve sample.mybatis.mapper.CityMapper.findByState
### The error occurred while executing a query
### SQL: select * from city where state = ?
### Cause: org.h2.jdbc.JdbcSQLException: Table "CITY" not found; SQL statement:
select * from city where state = ? [42102-193]
; bad SQL grammar []; nested exception is org.h2.jdbc.JdbcSQLException: Table "CITY" not found; SQL statement:
select * from city where state = ? [42102-193]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231) ~[spring-jdbc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[spring-jdbc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75) ~[mybatis-spring-1.3.0.jar:1.3.0]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:447) ~[mybatis-spring-1.3.0.jar:1.3.0]
	at com.sun.proxy.$Proxy40.selectOne(Unknown Source) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:167) ~[mybatis-spring-1.3.0.jar:1.3.0]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:82) ~[mybatis-3.4.1.jar:3.4.1]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53) ~[mybatis-3.4.1.jar:3.4.1]
	at com.sun.proxy.$Proxy43.findByState(Unknown Source) ~[na:na]
	at sample.mybatis.SampleMapperApplication.run(SampleMapperApplication.java:37) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	... 11 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: Table "CITY" not found; SQL statement:
select * from city where state = ? [42102-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.command.Parser.readTableOrView(Parser.java:5389) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.command.Parser.readTableFilter(Parser.java:1257) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1897) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2045) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.command.Parser.parseSelectSub(Parser.java:1891) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1709) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.command.Parser.parseSelect(Parser.java:1697) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.command.Parser.parsePrepared(Parser.java:445) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.command.Parser.parse(Parser.java:317) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.command.Parser.parse(Parser.java:289) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.command.Parser.prepareCommand(Parser.java:254) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.engine.Session.prepareLocal(Session.java:561) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.engine.Session.prepareCommand(Session.java:502) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1203) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73) ~[h2-1.4.193.jar:1.4.193]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:676) ~[h2-1.4.193.jar:1.4.193]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_73]
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126) ~[tomcat-jdbc-8.5.6.jar:na]
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108) ~[tomcat-jdbc-8.5.6.jar:na]
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81) ~[tomcat-jdbc-8.5.6.jar:na]
	at com.sun.proxy.$Proxy51.prepareStatement(Unknown Source) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_73]
	at org.apache.ibatis.logging.jdbc.ConnectionLogger.invoke(ConnectionLogger.java:55) ~[mybatis-3.4.1.jar:3.4.1]
	at com.sun.proxy.$Proxy52.prepareStatement(Unknown Source) ~[na:na]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:85) ~[mybatis-3.4.1.jar:3.4.1]
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88) ~[mybatis-3.4.1.jar:3.4.1]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59) ~[mybatis-3.4.1.jar:3.4.1]
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85) ~[mybatis-3.4.1.jar:3.4.1]
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62) ~[mybatis-3.4.1.jar:3.4.1]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324) ~[mybatis-3.4.1.jar:3.4.1]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.4.1.jar:3.4.1]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109) ~[mybatis-3.4.1.jar:3.4.1]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83) ~[mybatis-3.4.1.jar:3.4.1]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148) ~[mybatis-3.4.1.jar:3.4.1]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141) ~[mybatis-3.4.1.jar:3.4.1]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77) ~[mybatis-3.4.1.jar:3.4.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_73]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434) ~[mybatis-spring-1.3.0.jar:1.3.0]
	... 18 common frames omitted
```
And it seems spring boot did not found the import.sql. And how can I solve this problem,any  one could give me some tips? Thanks.

**Comment by kazuki43zoo** [comment]
Hi @QiuMing , Thanks for your reporting !!
This problem can resolve to change the `application.properties` as follow:

```diff
-spring.datasource.schema=import.sql
+spring.datasource.schema=classpath:import.sql
```

I will fix this ASAP.

Thanks again!

**Comment by kazuki43zoo** [comment]
Fixed via gh-122.
