### ISSUE TITLE
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.example.UserMapper.search

### ISSUE THREAD

**Issue by arjuncfe** [mybatis/spring-boot-starter#141]
Hi..  All  i am getting error given below : 
```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-02-23 17:05:21.202 ERROR 8772 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:779) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:760) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:747) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at com.example.MybatisDemoApplication.main(MybatisDemoApplication.java:22) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:na]
**Caused by: org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.example.UserMapper.search**
	at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:230) ~[mybatis-3.4.2.jar:3.4.2]
	at org.apache.ibatis.binding.MapperMethod.<init>(MapperMethod.java:48) ~[mybatis-3.4.2.jar:3.4.2]
	at org.apache.ibatis.binding.MapperProxy.cachedMapperMethod(MapperProxy.java:65) ~[mybatis-3.4.2.jar:3.4.2]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58) ~[mybatis-3.4.2.jar:3.4.2]
	at com.example.$Proxy47.search(Unknown Source) ~[na:na]
	at com.example.MybatisDemoApplication.lambda$demo$1(MybatisDemoApplication.java:40) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:776) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	... 11 common frames omitted
```

And my java class is:

```java
package com.example;


import ch.qos.logback.core.net.SyslogOutputStream;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.apache.ibatis.annotations.*;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

@SpringBootApplication
public class MybatisDemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(MybatisDemoApplication.class, args);

	}
	@Bean
	CommandLineRunner demo(UserMapper userMapper){
		return args->{
			List<User> users = Arrays.asList(new User("Arjun Singh" , "delhi",007L,1991),
			new User("Gagan Deep" , "delhi",8l,1997),
					new User("Amit" , "delhi",9l,1990)

			);
			System.out.print("------------------All users-----------------------");
			users.forEach(user -> {
				userMapper.insert(user);
				System.out.println(user.toString());
			});
			userMapper.findAll().forEach(System.out::println);
			System.out.print("------------------Search result-------------------");
			userMapper.search(0L,"Arjun Singh",null,0).forEach(System.out::println);

		};
	}

}
```
```java
@Mapper
interface UserMapper{
	@Options(useGeneratedKeys = true)
	@Insert("insert into user(name,address,id,dob) values (#{name},#{address},#{id},#{dob})")
	void insert(User user);
	@Select("select * from USER")
	Collection<User> findAll();
	@Delete("delete from USER where id = #{id}")
	void deleteById(long id);
	Collection<User> search( @Param("id") long id,@Param("name") String name,
							@Param("address") String address,@Param("dob") int dob
							);
}
```
```java
@Data
@AllArgsConstructor
@NoArgsConstructor
class User {
	private String name,address;
	private Long id;
	private int dob;
}
```

and UserMapper.xml code like this

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
        PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
        "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.example.UserMapper">

        <select id="search" resultType="com.example.User">
            select * from user
            <where>
                <if test="id!=0 and id!= null">
                    id = #{id}
                </if>
                <if test="name != null">
                    and name =  #{name}
                </if>
                <if test="address != null">
                    and  address = #{address}
                </if>
                <if test="dob!=0 and dob!= null">
                    and dob = #{dob}
                </if>
            </where>
        </select>
</mapper>
```

What is going wrong in this code 

-

**Comment by kazuki43zoo** [comment]
@arjuncfe 

Please provide reproduce project on GitHub.

**Comment by kazuki43zoo** [comment]
@arjuncfe 

I have one question.
Where you save the `UserMapper.xml` ?

**Comment by eddumelendez** [comment]
@arjuncfe `UserMapper.xml` must be in the same package that `UserMapper.java`

**Comment by arjuncfe** [comment]
Hi.. All this is my github project repository url :  git@github.com:arjuncfe/mybatis-demo.git

**Comment by eddumelendez** [comment]
Thanks to share a reproducible project @arjuncfe 

In `src/main/resources` your folder is named `com.example` (look at your system directory). Instead, you should have folder `com` and inside folder `example` then put you `UserMapper.xml` inside and run your app again.

**Comment by kazuki43zoo** [comment]
I've changed it as follow and it's work fine.

* `src/main/resources/com.example/` -> `src/main/resources/com/example`

Thanks.

**Comment by arjuncfe** [comment]
OK Thanks  it is working 👍

**Comment by Kheman9862** [comment]
> I've changed it as follow and it's work fine.
> 
> * `src/main/resources/com.example/` -> `src/main/resources/com/example/`
> 
> Thanks.

Lifesaver

**Comment by dcnis** [comment]
> Thanks to share a reproducible project @arjuncfe
> 
> In `src/main/resources` your folder is named `com.example` (look at your system directory). Instead, you should have folder `com` and inside folder `example` then put your `UserMapper.xml` inside and run your app again.

worked for me as well.

**Comment by qburst-abinpeter** [comment]
Great, this is working for me as well
