### ISSUE TITLE
Upgrade to Spring Boot 2.0.0.M5 on master

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/spring-boot-starter#193]
### Related Issues

* spring-projects/spring-boot#10702

**Comment by swachian** [comment]
```java
Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mybatis-org.mybatis.spring.boot.autoconfigure.MybatisProperties': Initialization of bean failed; nested exception is java.lang.StackOverflowError
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:581)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:91)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:367)

```

It's really an issue ：（

**Comment by kazuki43zoo** [comment]
Hi @swachian, I cannot reproduce your issue. Could you provide more detail information (providing reproduce project is very good!!)

**Comment by swachian** [comment]
It's ok when run in an application. However, it is wrong if I package the project in a war and deploy to tomcat 8.5. 

It went wrong at the step below
```
class org.apache.ibatis.session.Configuration mybatis.configuration.mapped-statements[0].configuration
```

**Comment by kazuki43zoo** [comment]
@swachian Could you provide a reproduce project on GitHub?

**Comment by kazuki43zoo** [comment]
@shroman And... Has occurred this issue only on Spring Boot 2.0.0.M5 or not?

**Comment by kazuki43zoo** [comment]
I've reopened this issue to investigate the report from @swachian.

**Comment by swachian** [comment]
Only on Spring Boot 2.0.0.M5 .
It's fine even on 2.0.0.M4. 
I'll try to make a reproduce project.

**Comment by swachian** [comment]
I push a reproduce project to https://github.com/swachian/springboot2.0.0.m5-wrong-with-mybatis.git

I made a deployable war as https://docs.spring.io/spring-boot/docs/2.0.0.M5/reference/html/howto-traditional-deployment.html said. It still run regularly as an application.
```java
@SpringBootApplication
public class M5Application  extends SpringBootServletInitializer {


	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(M5Application.class);
	}

	public static void main(String[] args) throws Exception {
		SpringApplication.run(M5Application.class, args);
	}
}
```

But get the error list when deploy the war to Tomcat 8.5.23

```
2017-10-18 15:23:21.649  INFO 14288 --- [ost-startStop-1] utoConfigurationReportLoggingInitializer :

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-10-18 15:23:21.659 ERROR 14288 --- [ost-startStop-1] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mybatis-org.mybatis.spring.boot.autoconfigure.MybatisProperties': Initialization of bean failed; nested exception is java.lang.StackOverflowError
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:723) ~[spring-beans-5.0.0.RELEASE.jar:5.0.0.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:192) ~[spring-beans-5.0.0.RELEASE.jar:5.0.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1269) ~[spring-beans-5.0.0.RELEASE.jar:5.0.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1126) ~[spring-beans-5.0.0.RELEASE.jar:5.0.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-5.0.0.RELEASE.jar:5.0.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502) ~[spring-beans-5.0.0.RELEASE.jar:5.0.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312) ~[spring-beans-5.0.0.RELEASE.jar:5.0.0.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.0.RELEASE.jar:5.0.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.0.0.RELEASE.jar:5.0.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-5.0.0.RELEASE.jar:5.0.0.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:756) ~[spring-beans-5.0.0.RELEASE.jar:5.0.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.0.0.RELEASE.jar:5.0.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.0.0.RELEASE.jar:5.0.0.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:122) ~[spring-boot-2.0.0.M5.jar:2.0.0.M5]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.0.0.M5.jar:2.0.0.M5]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386) ~[spring-boot-2.0.0.M5.jar:2.0.0.M5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) ~[spring-boot-2.0.0.M5.jar:2.0.0.M5]
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:155) [spring-boot-2.0.0.M5.jar:2.0.0.M5]
```

**Comment by kazuki43zoo** [comment]
Hi @swachian , thanks for providing reproduce project. I will check at later (out of business time!)

**Comment by kazuki43zoo** [comment]
I've created spring-projects/spring-boot#10702.
The root cause has not been found yet.

**Comment by kazuki43zoo** [comment]
Current status: Under waiting for feedback from spring boot team and investigating.

**Comment by kazuki43zoo** [comment]
Hi @shroman, I found a temporary workaround for this issue.
See https://github.com/spring-projects/spring-boot/issues/10702#issuecomment-338361007.

**Comment by kazuki43zoo** [comment]
I've closed this.
The StackOverflowError issue manages on #196
