### ISSUE TITLE
Error updating database.  Cause: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

### ISSUE THREAD

**Issue by 80904001** [mybatis/spring-boot-starter#223]
regarding the issue title, I've met the problem when I use Mybatis springboot starter, below is my configration:

```xml
<dependency>
         <groupId>org.mybatis.spring.boot</groupId>
	<artifactId>mybatis-spring-boot-starter</artifactId>
	<version>1.3.2</version>
</dependency>
```

in my Mapper.xml I've written SQL like this:

```xml
<!-- 批量保存 -->
  <insert id="batchSave" parameterType="com.vip.jinsk.model.biz.ProjectNewEvalSystem">
    <foreach collection="list" item="item" index="index">
      INSERT INTO T_BIZ_PN_EVAL_SYSTEM (ID, PROJECT_ID, PROJECT_NAME,
      SUB_SYSTEM, MODULE, DESCRIPTION,
      AMOUNT, AMOUNT_EXPLAIN, CREATE_USER_ID,
      CREATE_USER_NAME, CREATE_TIME, UPDATE_USER_ID,
      UPDATE_USER_NAME, UPDATE_TIME, DELETED)
      VALUES
      (#{item.id,jdbcType=VARCHAR}, #{item.projectId,jdbcType=VARCHAR}, #{item.projectName,jdbcType=VARCHAR},
      #{item.subSystem,jdbcType=VARCHAR}, #{item.module,jdbcType=VARCHAR}, #{item.description,jdbcType=VARCHAR},
      #{item.amount,jdbcType=DECIMAL}, #{item.amountExplain,jdbcType=VARCHAR}, #{item.createUserId,jdbcType=VARCHAR},
      #{item.createUserName,jdbcType=VARCHAR}, #{item.createTime,jdbcType=VARCHAR}, #{item.updateUserId,jdbcType=VARCHAR},
      #{item.updateUserName,jdbcType=VARCHAR}, #{item.updateTime,jdbcType=VARCHAR}, #{item.deleted,jdbcType=DECIMAL}
      )
    </foreach>
    SELECT 1 FROM DUAL
  </insert>
```

the error info and exception stack as below:

```
2018-03-29 10:25:41.714  INFO 91048 --- [http-nio-8080-exec-1] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
2018-03-29 10:25:44.343 DEBUG 91048 --- [http-nio-8080-exec-1] c.v.j.c.p.c.d.m.b.P.batchSave            : ==>  Preparing: INSERT ALL INTO T_BIZ_PN_EVAL_SYSTEM (ID, PROJECT_ID, PROJECT_NAME, SUB_SYSTEM, MODULE, DESCRIPTION, AMOUNT, AMOUNT_EXPLAIN, CREATE_USER_ID, CREATE_USER_NAME, CREATE_TIME, UPDATE_USER_ID, UPDATE_USER_NAME, UPDATE_TIME, DELETED) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) INTO T_BIZ_PN_EVAL_SYSTEM (ID, PROJECT_ID, PROJECT_NAME, SUB_SYSTEM, MODULE, DESCRIPTION, AMOUNT, AMOUNT_EXPLAIN, CREATE_USER_ID, CREATE_USER_NAME, CREATE_TIME, UPDATE_USER_ID, UPDATE_USER_NAME, UPDATE_TIME, DELETED) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) SELECT 1 FROM DUAL 
2018-03-29 10:25:44.397 DEBUG 91048 --- [http-nio-8080-exec-1] c.v.j.c.p.c.d.m.b.P.batchSave            : ==> Parameters: P-N-20180325152133239-0021(String), P-N-20180325152133239(String), 项目申报系统(String), 申报子系统(String), 登录模板(String), 登录申报子系统(String), 2(Short), 10人/天(String), jinshangkun(String), 金尚坤(String), 2018-03-29 10:25:44(String), jinshangkun(String), 金尚坤(String), 2018-03-29 10:25:44(String), 0(Integer), P-N-20180325152133239-0022(String), P-N-20180325152133239(String), 项目申报系统(String), 申报子系统(String), 首页模板(String), 登录申报子系统(String), 3(Short), 11人/天(String), jinshangkun(String), 金尚坤(String), 2018-03-29 10:25:44(String), jinshangkun(String), 金尚坤(String), 2018-03-29 10:25:44(String), 0(Integer)
2018-03-29 10:25:44.520  INFO 91048 --- [http-nio-8080-exec-1] o.s.b.f.xml.XmlBeanDefinitionReader      : Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
2018-03-29 10:25:44.545  INFO 91048 --- [http-nio-8080-exec-1] o.s.jdbc.support.SQLErrorCodesFactory    : SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana]
2018-03-29 10:25:44.612 ERROR 91048 --- [http-nio-8080-exec-1] c.v.j.c.p.c.c.e.GlobalExceptionHandler   : 数据库访问发生异常 ==>

org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

### The error may involve com.vip.jinsk.dao.mapper.biz.ProjectNewEvalSystemMapper.batchSave-Inline
### The error occurred while setting parameters
### SQL: INSERT ALL              INTO T_BIZ_PN_EVAL_SYSTEM (ID, PROJECT_ID, PROJECT_NAME,       SUB_SYSTEM, MODULE, DESCRIPTION,       AMOUNT, AMOUNT_EXPLAIN, CREATE_USER_ID,       CREATE_USER_NAME, CREATE_TIME, UPDATE_USER_ID,       UPDATE_USER_NAME, UPDATE_TIME, DELETED)       VALUES       (?, ?, ?,       ?, ?, ?,       ?, ?, ?,       ?, ?, ?,       ?, ?, ?       )              INTO T_BIZ_PN_EVAL_SYSTEM (ID, PROJECT_ID, PROJECT_NAME,       SUB_SYSTEM, MODULE, DESCRIPTION,       AMOUNT, AMOUNT_EXPLAIN, CREATE_USER_ID,       CREATE_USER_NAME, CREATE_TIME, UPDATE_USER_ID,       UPDATE_USER_NAME, UPDATE_TIME, DELETED)       VALUES       (?, ?, ?,       ?, ?, ?,       ?, ?, ?,       ?, ?, ?,       ?, ?, ?       )           SELECT 1 FROM DUAL
### Cause: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:91)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy80.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:58)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy84.batchSave(Unknown Source)
	at com.vip.jinsk.cq.project.cqsra.service.base.BaseService.saveBatch(BaseService.java:43)
	at com.vip.jinsk.cq.project.cqsra.service.base.BaseService$$FastClassBySpringCGLIB$$a9051eaa.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.vip.jinsk.cq.project.cqsra.service.biz.impl.ProjectNewEvalSystemServiceImpl$$EnhancerBySpringCGLIB$$c7b67fa3.saveBatch(<generated>)
	at com.vip.jinsk.service.biz.impl.ProjectBaseInfoServiceImpl.saveProjectNewEvalInfo(ProjectBaseInfoServiceImpl.java:103)
	at com.vip.jinsk.cq.project.cqsra.service.biz.impl.ProjectBaseInfoServiceImpl$$FastClassBySpringCGLIB$$adbd952d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.vip.jinsk.service.biz.impl.ProjectBaseInfoServiceImpl$$EnhancerBySpringCGLIB$$cfb7a8f1.saveProjectNewEvalInfo(<generated>)
	at com.vip.jinsk.cq.project.cqsra.controller.biz.ProjectInitApiController.saveDraftEvalInfo(ProjectInitApiController.java:284)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:164)
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1044)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1329)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3685)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1376)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy110.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy108.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 86 common frames omitted

2018-03-29 10:25:44.637  WARN 91048 --- [http-nio-8080-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by Handler execution: org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

### The error may involve com.vip.jinsk.dao.mapper.biz.ProjectNewEvalSystemMapper.batchSave-Inline
### The error occurred while setting parameters
### SQL: INSERT ALL              INTO T_BIZ_PN_EVAL_SYSTEM (ID, PROJECT_ID, PROJECT_NAME,       SUB_SYSTEM, MODULE, DESCRIPTION,       AMOUNT, AMOUNT_EXPLAIN, CREATE_USER_ID,       CREATE_USER_NAME, CREATE_TIME, UPDATE_USER_ID,       UPDATE_USER_NAME, UPDATE_TIME, DELETED)       VALUES       (?, ?, ?,       ?, ?, ?,       ?, ?, ?,       ?, ?, ?,       ?, ?, ?       )              INTO T_BIZ_PN_EVAL_SYSTEM (ID, PROJECT_ID, PROJECT_NAME,       SUB_SYSTEM, MODULE, DESCRIPTION,       AMOUNT, AMOUNT_EXPLAIN, CREATE_USER_ID,       CREATE_USER_NAME, CREATE_TIME, UPDATE_USER_ID,       UPDATE_USER_NAME, UPDATE_TIME, DELETED)       VALUES       (?, ?, ?,       ?, ?, ?,       ?, ?, ?,       ?, ?, ?,       ?, ?, ?       )           SELECT 1 FROM DUAL
### Cause: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended
```

Is anyone who occurred the same error in this situation?  
Thank you all in advance for giving me some solutions!

**Comment by kazuki43zoo** [comment]
Could you execute your sql using pure JDBC (without MyBatis)?

**Comment by 80904001** [comment]
@kazuki43zoo  yeah, this problem was solved by adding useGeneratedKeys="false" in my mapper.xml of insert id="batchSave" section, thank you all the same.

**Comment by ruchiraPeiris** [comment]
I am getting "the following has evaluated to null or missing" with same configurations. Could you please advise?
