### ISSUE TITLE
Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required

### ISSUE THREAD

**Issue by FlowerWrong** [mybatis/spring-boot-starter#224]
* Spring Boot v2.0.1.RELEASE
* mybatis-spring-boot-starter 1.3.2

It worked well in controller, but controller test failed. also, mapper test worked well.

## SessionControllerTests

```java
package com.github.flowerwrong.admin.controller;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import org.springframework.test.web.servlet.result.MockMvcResultMatchers;

import static org.assertj.core.api.Assertions.*;

@RunWith(SpringRunner.class)
@WebMvcTest(SessionController.class)
public class SessionControllerTests {

  @Autowired
  private MockMvc mockMvc;

  @Test
  public void indexPage() throws Exception {
    assertThat(mockMvc).isNotNull();
    mockMvc.perform(MockMvcRequestBuilders.get("/login"))
        .andExpect(MockMvcResultMatchers.status().isOk());
  }
}

```

## error log

```
2018-04-08 17:38:46.442  INFO 75683 --- [           main] c.g.f.a.c.SessionControllerTests         : Starting SessionControllerTests on kingdeMacBook-Pro.local with PID 75683 (started by kingyang in /Users/kingyang/dev/java/tyrannosaurus/admin)
2018-04-08 17:38:46.443 DEBUG 75683 --- [           main] c.g.f.a.c.SessionControllerTests         : Running with Spring Boot v2.0.1.RELEASE, Spring v5.0.5.RELEASE
2018-04-08 17:38:46.444  INFO 75683 --- [           main] c.g.f.a.c.SessionControllerTests         : The following profiles are active: development,local
2018-04-08 17:38:46.764  WARN 75683 --- [           main] o.s.w.c.s.GenericWebApplicationContext   : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'baseMapper' defined in file [/Users/kingyang/dev/java/tyrannosaurus/model/target/classes/com/github/flowerwrong/model/common/mapper/BaseMapper.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
2018-04-08 17:38:46.775 ERROR 75683 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'baseMapper' defined in file [/Users/kingyang/dev/java/tyrannosaurus/model/target/classes/com/github/flowerwrong/model/common/mapper/BaseMapper.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required

...


Caused by: java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
	at org.springframework.util.Assert.notNull(Assert.java:193)
	at org.mybatis.spring.support.SqlSessionDaoSupport.checkDaoConfig(SqlSessionDaoSupport.java:74)
	at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:73)
	at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1761)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1698)
	... 43 common frames omitted
```

**Comment by kazuki43zoo** [comment]
Could you provide a reproduce project via GitHub?

**Comment by kazuki43zoo** [comment]
Or please try mybatis-spring-boot-test.

* http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-test-autoconfigure

**Comment by FlowerWrong** [comment]
I have wrote a demo, it worked well. 😢 , So sad.

**Comment by FlowerWrong** [comment]
After I add some code, it worked.

```java
package com.github.flowerwrong.model;


import javax.sql.DataSource;
import org.apache.ibatis.session.SqlSessionFactory;
import org.mybatis.spring.SqlSessionFactoryBean;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.PlatformTransactionManager;

@SpringBootApplication
@MapperScan(basePackages = {"com.github.flowerwrong.model.mapper"})
public class App {

  public static void main(String[] args) {
    SpringApplication.run(App.class, args);
  }

  private final static String DATASOURCE_PREIFX = "spring.datasource";

  @Bean
  @ConfigurationProperties(prefix = DATASOURCE_PREIFX)
  public DataSource dataSource() {
    return new org.apache.tomcat.jdbc.pool.DataSource();
  }

  @Bean
  public SqlSessionFactory sqlSessionFactoryBean() throws Exception {

    SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
    sqlSessionFactoryBean.setDataSource(dataSource());

    PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();

    sqlSessionFactoryBean.setMapperLocations(resolver.getResources("classpath:/mapper/*.xml"));

    return sqlSessionFactoryBean.getObject();
  }

  @Bean
  public PlatformTransactionManager transactionManager() {
    return new DataSourceTransactionManager(dataSource());
  }
}
```

Important code is 
```java
@Bean
  @ConfigurationProperties(prefix = DATASOURCE_PREIFX)
  public DataSource dataSource() {
    return new org.apache.tomcat.jdbc.pool.DataSource();
  }

  @Bean
  public SqlSessionFactory sqlSessionFactoryBean() throws Exception {

    SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
    sqlSessionFactoryBean.setDataSource(dataSource());

    PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();

    sqlSessionFactoryBean.setMapperLocations(resolver.getResources("classpath:/mapper/*.xml"));

    return sqlSessionFactoryBean.getObject();
  }

  @Bean
  public PlatformTransactionManager transactionManager() {
    return new DataSourceTransactionManager(dataSource());
  }

// pom.xml
<dependency>
      <groupId>org.apache.tomcat</groupId>
      <artifactId>tomcat-jdbc</artifactId>
      <version>9.0.7</version>
</dependency>
```

I do not know why. But the demo project worked well without code above.

**Comment by kazuki43zoo** [comment]
Could you provide a demo project via GitHub?

**Comment by FlowerWrong** [comment]
[my project](https://github.com/FlowerWrong/tyrannosaurus)

[code commit to fix test](https://github.com/FlowerWrong/tyrannosaurus/commit/f783633ab30f38972f692f435d165326ec8c316a)

**Comment by kazuki43zoo** [comment]
I've reproduced on the following demo:

```java
package com.example.gh224mybatisspringbootstarter;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import org.springframework.test.web.servlet.result.MockMvcResultMatchers;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RunWith(SpringRunner.class)
@WebMvcTest(Gh224MybatisSpringBootStarterApplicationTests.MyController.class)
@MapperScan("com.example.gh224mybatisspringbootstarter")
public class Gh224MybatisSpringBootStarterApplicationTests {

	@Autowired
	private MockMvc mockMvc;

	@Test
	public void contextLoads() throws Exception {
		mockMvc.perform(MockMvcRequestBuilders.get("/hello"))
			.andExpect(MockMvcResultMatchers.status().isOk())
			.andExpect(MockMvcResultMatchers.content().string("hello"));
	}

	@RestController
	static class MyController {

		@GetMapping("/hello")
		public String hello() {
			return "hello";
		}

	}

	@Mapper
	interface MyMapper {
		@Select("SELECT #{number}")
		int selectNumber(int number);
	}

}
```

And I 've resolved this issue using mybatis-spring-boot-test-starter as follow:

```diff
package com.example.gh224mybatisspringbootstarter;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mybatis.spring.annotation.MapperScan;
+import org.mybatis.spring.boot.test.autoconfigure.AutoConfigureMybatis;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import org.springframework.test.web.servlet.result.MockMvcResultMatchers;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RunWith(SpringRunner.class)
@WebMvcTest(Gh224MybatisSpringBootStarterApplicationTests.MyController.class)
+@AutoConfigureMybatis
@MapperScan("com.example.gh224mybatisspringbootstarter")
public class Gh224MybatisSpringBootStarterApplicationTests {

	@Autowired
	private MockMvc mockMvc;

	@Test
	public void contextLoads() throws Exception {
		mockMvc.perform(MockMvcRequestBuilders.get("/hello"))
			.andExpect(MockMvcResultMatchers.status().isOk())
			.andExpect(MockMvcResultMatchers.content().string("hello"));
	}

	@RestController
	static class MyController {

		@GetMapping("/hello")
		public String hello() {
			return "hello";
		}

	}

	@Mapper
	interface MyMapper {
		@Select("SELECT #{number}")
		int selectNumber(int number);
	}

}
```

> I do not know why.

The `@WebMvcTest` cannot configure beans for MyBatis, therefore you should configure beansfor MyBatis. I will introduce the mybatis-spring-boot-test-starter project as method of bean definitions for MyBatis on test class.

> But the demo project worked well without code above.

I guess that your demo project does not scan expressly Mapper using `@MapperScan` annotation.

**Comment by FlowerWrong** [comment]
Thanks a lot, it worked.

**Comment by kazuki43zoo** [comment]
@FlowerWrong Thanks for your reporting!
I've created #225 for updating documentation.

**Comment by KimRasak** [comment]
omg, I finally work this out. Thanks.
