### ISSUE TITLE
Using Spring Boot Test Starter and parameterType="map"

### ISSUE THREAD

**Issue by joannbrereton** [mybatis/spring-boot-starter#247]
I am trying to test an xml based Mapper that I have for my project.   In the xml is something that looks like this.

```
...
 <sql id="Example_Clause_Date_Team">
    <where>
        GAME_DATE = #{date,jdbcType=DATE}

      <choose>

        <when test="matchHomeAway == true">
          AND ( HOME_TM_ID = #{homeTeamId,jdbcType=INTEGER} AND AWAY_TM_ID= #{awayTeamId, jdbcType=INTEGER} )
         </when>

        <when test="matchHomeAway == false">
          AND ( ( HOME_TM_ID = #{homeTeamId,jdbcType=INTEGER} AND AWAY_TM_ID= #{awayTeamId, jdbcType=INTEGER} ) OR
                ( HOME_TM_ID = #{awayTeamId,jdbcType=INTEGER} AND AWAY_TM_ID= #{homeTeamId, jdbcType=INTEGER} )
          )
        </when>

        <otherwise />
      </choose>

    </where>
  </sql>
...
 <select id="selectGamesByDateAndTeams" parameterMap="map" resultMap="GameMap">
    select
    <include refid="Base_Column_List" />
    FROM game
    LEFT JOIN team away_team ON away_team.ID=game.AWAY_TM_ID
    LEFT JOIN team home_team ON home_team.ID=game.HOME_TM_ID
    LEFT JOIN venue ON venue.VENUE_ID=game.VENUE_ID
    <include refid="Example_Clause_Date_Team" />
    ORDER BY EASTERN_TIME ASC
  </select>
...
```

The java interface for that particular query looks like this.

```
  List<Game> selectGamesByDateAndTeams(@Param("date") LocalDate date,
                                         @Param("homeTeamId") Integer homeTeamId,
                                         @Param("awayTeamId") Integer awayTeamId,
                                         @Param("matchHomeAway") Boolean matchHomeAway);

```

The selectGamesByDateAndTeams query works fine within regular code, but when I write a test for it using spring boot mybatis test starter like this

```
...

    @Test
    public void gameDbMapperExistsTest() {
        assertThat(gameDbMapper,notNullValue());
    }

    @Test
    public void gamesWereSaved() {
        List<com.mlb.best.domain.Game> games = gameDbMapper.selectGamesByDateAndTeams(LocalDate.of(2018,1,1),1,2,true);
        assertThat(games, hasSize(2));
    }

```

, the gameMapperExistsTest works fine but the gamesWereSaved test fails with

```
org.apache.ibatis.builder.IncompleteElementException: Could not find parameter map com.mlb.best.mapper.GameDbMapper.map

	at org.apache.ibatis.builder.MapperBuilderAssistant.getStatementParameterMap(MapperBuilderAssistant.java:320)
	at org.apache.ibatis.builder.MapperBuilderAssistant.addMappedStatement(MapperBuilderAssistant.java:296)
	at org.apache.ibatis.builder.xml.XMLStatementBuilder.parseStatementNode(XMLStatementBuilder.java:109)
	at org.apache.ibatis.session.Configuration.buildAllStatements(Configuration.java:788)
	at org.apache.ibatis.session.Configuration.hasStatement(Configuration.java:758)
	at org.apache.ibatis.session.Configuration.hasStatement(Configuration.java:753)
	at org.apache.ibatis.binding.MapperMethod$SqlCommand.resolveMappedStatement(MapperMethod.java:247)
	at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:217)
	at org.apache.ibatis.binding.MapperMethod.<init>(MapperMethod.java:48)
	at org.apache.ibatis.binding.MapperProxy.cachedMapperMethod(MapperProxy.java:65)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58)
	at com.sun.proxy.$Proxy159.selectGamesByDateAndTeams(Unknown Source)
	at com.mlb.best.mapper.GameDbMapperTest.gamesWereSaved(GameDbMapperTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalArgumentException: Parameter Maps collection does not contain value for com.mlb.best.mapper.GameDbMapper.map
	at org.apache.ibatis.session.Configuration$StrictMap.get(Configuration.java:888)
	at org.apache.ibatis.session.Configuration.getParameterMap(Configuration.java:660)
	at org.apache.ibatis.builder.MapperBuilderAssistant.getStatementParameterMap(MapperBuilderAssistant.java:318)
	... 41 more
```

Is there something special about getting parameterType="map" to work within the Spring Boot MyBatis test stuff?  What am I doing wrong here?

**Comment by joannbrereton** [comment]
Question withdrawn.  Realized I could just leave parameterType="map" off.
