### ISSUE TITLE
spring-boot-autoconfigure didn't create SqlSessionFactory bean on some env.

### ISSUE THREAD

**Issue by dingjs** [mybatis/spring-boot-starter#264]
Hi, I have a spring-boot 2.0.4 project,using mybatis-spring-boot-starter-1.3.2. 
The project runs fine on my windows and linux computer. 
But if I use `jar xvf` extract the project,then I use `jar cvmf0 /META-INF/MANIFEST.MF` to recover the jar.
Although these two jars are all the same.But the later one can't run properly.
The stacktrace is
 ```
Caused by: java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
        at org.springframework.util.Assert.notNull(Assert.java:193) ~[spring-core-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
        at org.mybatis.spring.support.SqlSessionDaoSupport.checkDaoConfig(SqlSessionDaoSupport.java:74) ~[mybatis-spring-1.3.2.jar!/:1.3.2]
        at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:73) ~[mybatis-spring-1.3.2.jar!/:1.3.2]
        at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44) ~[spring-tx-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1758) ~[spring-beans-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1695) ~[spring-beans-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
        ... 108 common frames omitted
```

## Expected Behavior
     `MybatisAutoConfiguration` should AutoConfigureAfter `DataSourceAutoConfiguration`, and create `sqlSessionFactory`.

## Current Behavior
    The debug logs : 
```
   MybatisAutoConfiguration:
      Did not match:
         - @ConditionalOnBean (types: javax.sql.DataSource; SearchStrategy: all) **did not find any beans of type javax.sql.DataSource** (OnBeanCondition)
      Matched:
         - @ConditionalOnClass found required classes 'org.apache.ibatis.session.SqlSessionFactory', 'org.mybatis.spring.SqlSessionFactoryBean'; @ConditionalOnMissingClass did not find unwanted class (OnClassCondition)
```
     The right debug logs : 
```
	MybatisAutoConfiguration matched:
      - @ConditionalOnClass found required classes 'org.apache.ibatis.session.SqlSessionFactory', 'org.mybatis.spring.SqlSessionFactoryBean'; @ConditionalOnMissingClass did not find unwanted class (OnClassCondition)
      - @ConditionalOnBean (types: javax.sql.DataSource; SearchStrategy: all) **found bean 'dataSource'** (OnBeanCondition)

   MybatisAutoConfiguration#sqlSessionFactory matched:
      - @ConditionalOnMissingBean (types: org.apache.ibatis.session.SqlSessionFactory; SearchStrategy: all) did not find any beans (OnBeanCondition)

   MybatisAutoConfiguration#sqlSessionTemplate matched:
      - @ConditionalOnMissingBean (types: org.mybatis.spring.SqlSessionTemplate; SearchStrategy: all) did not find any beans (OnBeanCondition)
```

## Possible Solution
   I can define  `datasource` bean by myself.I just can't figure out why it didn't work.The only difference is in the wrong jar seems like loading the `BOOT-INF/lib` jars order by Alphabetical.
```
>java -Ddebug -jar jyyw.jar
DEBUG StatusLogger org.slf4j.helpers.Log4jLoggerFactory is not on classpath. Good!
2018-10-19 17:53:41.743 DEBUG 259520 --- [           main] .c.l.ClasspathLoggingApplicationListener : Application started with classpath: [jar:file:/opt/projects/jyyw.jar!/BOOT-INF/classes!/,
 jar:file:/opt/projects/jyyw.jar!/BOOT-INF/lib/annotations-3.0.1.jar!/,
 jar:file:/opt/projects/jyyw.jar!/BOOT-INF/lib/a-code-6.0.10.jar!/,
 jar:file:/opt/projects/jyyw.jar!/BOOT-INF/lib/a-code-starter-6.0.10.jar!/,
 ......
 jar:file:/opt/projects/jyyw.jar!/BOOT-INF/lib/spring-boot-2.0.4.RELEASE.jar!/,
```

and the right jar loads the `BOOT-INF/lib` jars differently,the spring-boot jars are on the top.
```
>java -jar -Ddebug jyyw.jar
DEBUG StatusLogger org.slf4j.helpers.Log4jLoggerFactory is not on classpath. Good!
2018-10-19 17:33:47.892 DEBUG 277596 --- [           main] .c.l.ClasspathLoggingApplicationListener : Application started with classpath: [jar:file:/opt/projects/jyyw.jar!/BOOT-INF/classes!/,
 jar:file:/opt/projects/jyyw.jar!/BOOT-INF/lib/spring-boot-2.0.4.RELEASE.jar!/,
 jar:file:/opt/projects/jyyw.jar!/BOOT-INF/lib/spring-context-5.0.8.RELEASE.jar!/,
 jar:file:/opt/projects/jyyw.jar!/BOOT-INF/lib/spring-boot-autoconfigure-2.0.4.RELEASE.jar!/,
 jar:file:/opt/projects/jyyw.jar!/BOOT-INF/lib/spring-boot-starter-aop-2.0.4.RELEASE.jar!/,
 jar:file:/opt/projects/jyyw.jar!/BOOT-INF/lib/spring-boot-starter-2.0.4.RELEASE.jar!/,
 jar:file:/opt/projects/jyyw.jar!/BOOT-INF/lib/spring-boot-starter-logging-2.0.4.RELEASE.jar!/,
 
```

## My Environment
* mybatis-3.4.6,mybatis-spring-1.3.2,mybatis-spring-boot-autoconfigure-1.3.2,mybatis-spring-boot-starter-1.3.2
* spring-boot-2.0.4
* jdk 1.8

**Comment by kazuki43zoo** [comment]
> But if I use jar xvf extract the project,then I use jar cvmf0 /META-INF/MANIFEST.MF to recover the jar.

What do you want to doing? I don't understand it ...
Do you want to change the `/META-INF/MANIFEST.MF`? Could you explain more detail?

**Comment by dingjs** [comment]
> > But if I use jar xvf extract the project,then I use jar cvmf0 /META-INF/MANIFEST.MF to recover the jar.
> 
> What do you want to doing? I don't understand it ...
> Do you want to change the `/META-INF/MANIFEST.MF`? Could you explain more detail?

No, I just make sure I didn't change anything,just extract the jar and recover it.Although these two jars are the same,but the second one went wrong.
`jar cvmf0 /META-INF/MANIFEST.MF` just make sue the jar command use the original MANIFEST.MF instead of create a new one.

**Comment by kazuki43zoo** [comment]
I've closed this issue because I think this issue does not belong with this project. If you think it is a problem, I propose to create a new issue on spring-boot.
