### ISSUE TITLE
Mybatis Spring boot calling SQL function not working

### ISSUE THREAD

**Issue by manrajesh** [mybatis/spring-boot-starter#276]
HI, 

I have sample spring-boot Project where i call SQL function not working. I am not sure it is a problem with Mybatis spring boot starter or my code level issue. I have sample demo spring boot app giving this exception when you try to hit the rest service endpoint. You can clone my github repo at https://github.com/manrajesh/demo .

I am getting the below error while try to call that function.

```
2018-10-30 15:24:18.991  INFO 32549 --- [nio-8080-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2018-10-30 15:24:21.162  INFO 32549 --- [nio-8080-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2018-10-30 15:24:21.893  INFO 32549 --- [nio-8080-exec-1] o.s.b.f.xml.XmlBeanDefinitionReader      : Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
2018-10-30 15:24:22.374 ERROR 32549 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.jdbc.UncategorizedSQLException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: cursor "<unnamed portal 1>" does not exist
### The error may exist in com/example/demo/Mapper.xml
### The error may involve com.example.demo.Mapper.getData-Inline
### The error occurred while setting parameters
### SQL: {               call ETADATA.MV_GET_UI_PAGEC(1340,         10572,         ?,         ?,         0,         25,         ?,         ?,         ?,         ?,         ?,         ?,         ?)                 }
### Cause: org.postgresql.util.PSQLException: ERROR: cursor "<unnamed portal 1>" does not exist
; uncategorized SQLException; SQL state [34000]; error code [0]; ERROR: cursor "<unnamed portal 1>" does not exist; nested exception is org.postgresql.util.PSQLException: ERROR: cursor "<unnamed portal 1>" does not exist] with root cause

org.postgresql.util.PSQLException: ERROR: cursor "<unnamed portal 1>" does not exist
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440) ~[postgresql-42.2.5.jar:42.2.5]
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183) ~[postgresql-42.2.5.jar:42.2.5]
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308) ~[postgresql-42.2.5.jar:42.2.5]
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.5.jar:42.2.5]
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.5.jar:42.2.5]
    at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307) ~[postgresql-42.2.5.jar:42.2.5]
    at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293) ~[postgresql-42.2.5.jar:42.2.5]
    at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270) ~[postgresql-42.2.5.jar:42.2.5]
    at org.postgresql.jdbc.PgConnection.execSQLQuery(PgConnection.java:417) ~[postgresql-42.2.5.jar:42.2.5]
    at org.postgresql.jdbc.PgResultSet.internalGetObject(PgResultSet.java:250) ~[postgresql-42.2.5.jar:42.2.5]
    at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:
```

Any help appreciated.
Thanks

**Comment by kazuki43zoo** [comment]
Close because this issue does not belong this project.
If you need help this issue, please post a question to [the mailing list of mybatis user](https://groups.google.com/forum/#!forum/mybatis-user).

Suggestion: 
Could provide a DLL & DML(create table, create function and insert statement for test) ?
