### ISSUE TITLE
Mybatis-spring-boot-starter: 1.3.2 upgrade 2.0.0 program error

### ISSUE THREAD

**Issue by zhangjiaxin281** [mybatis/spring-boot-starter#299]
**gradle info**
```
plugins {
    id 'java'
}

group 'com.sunvua'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    maven { url "http://maven.aliyun.com/nexus/content/groups/public" }
    jcenter()
}

dependencies {
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-test', version: '2.1.3.RELEASE'
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-parent', version: '2.1.3.RELEASE'
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: '2.1.3.RELEASE'
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-jdbc', version: '2.1.3.RELEASE'
    compile('org.apache.commons:commons-pool2:2.5.0')
//    compile('org.mybatis.spring.boot:mybatis-spring-boot-starter:1.3.2')
    compile('org.mybatis.spring.boot:mybatis-spring-boot-starter:2.0.0')
    compile('mysql:mysql-connector-java:6.0.6')
}
```
**application.yml**
```
server:
  port: 6868
spring:
  datasource:
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  config-location: classpath:/mybatis-config.xml
```
**mybatis-config.xml**
```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration PUBLIC "-//mybatis.org//DTD Config 3.0//EN" "http://mybatis.org/dtd/mybatis-3-config.dtd">
<configuration>
    <settings>
    <setting name="logImpl" value="STDOUT_LOGGING"/>
    </settings>
</configuration>
```
**error info**
```
2019-03-09 13:27:50.034 default [main] INFO  com.sunvua.Application - Starting Application on zjx with PID 14172 (E:\IntelliJWorkspace\rabbitmq-hello\out\production\classes started by zjx in E:\IntelliJWorkspace\rabbitmq-hello)
2019-03-09 13:27:50.039 default [main] INFO  com.sunvua.Application - No active profile set, falling back to default profiles: default
2019-03-09 13:27:51.538 default [main] WARN  o.m.s.mapper.ClassPathMapperScanner - No MyBatis mapper was found in '[com.sunvua]' package. Please check your configuration.
2019-03-09 13:27:53.169 default [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 6868 (http)
2019-03-09 13:27:53.237 default [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-6868"]
2019-03-09 13:27:53.250 default [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
2019-03-09 13:27:53.251 default [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.16]
2019-03-09 13:27:53.274 default [main] INFO  o.a.c.core.AprLifecycleListener - The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [C:\Program Files\Java\jdk1.8.0_144\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Java\jdk1.8.0_144\bin;C:\Program Files\Java\jdk1.8.0_144\jre\bin;D:\maven\apache-maven-3.6.0\bin;D:\gradle\gradle-4.6\\bin;D:\Git\cmd;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\scala\bin;D:\TortoiseGit\bin;D:\nodejs\;C:\Users\zjx\bin\Sencha\Cmd;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;D:\Program Files\Calibre2\;C:\Users\zjx\AppData\Local\Microsoft\WindowsApps;C:\Users\zjx\AppData\Roaming\npm;.]
2019-03-09 13:27:53.587 default [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
2019-03-09 13:27:53.587 default [main] INFO  o.s.web.context.ContextLoader - Root WebApplicationContext: initialization completed in 3438 ms
2019-03-09 13:27:54.413 default [main] INFO  o.s.s.c.ThreadPoolTaskExecutor - Initializing ExecutorService 'applicationTaskExecutor'
2019-03-09 13:27:54.668 default [main] INFO  o.s.b.a.w.s.WelcomePageHandlerMapping - Adding welcome page: class path resource [public/index.html]
2019-03-09 13:27:55.026 default [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is java.lang.NullPointerException
2019-03-09 13:27:55.028 default [main] INFO  o.s.s.c.ThreadPoolTaskExecutor - Shutting down ExecutorService 'applicationTaskExecutor'
2019-03-09 13:27:55.037 default [main] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]
2019-03-09 13:27:55.093 default [main] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-03-09 13:27:55.118 default [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:607)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1305)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1144)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:549)
	at org.springframework.context.support.AbstractApplicationContext.jrLockAndRefresh(AbstractApplicationContext.java:40002)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:41008)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.sunvua.Application.main(Application.java:9)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	... 21 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.mybatis.spring.SqlSessionFactoryBean.buildSqlSessionFactory(SqlSessionFactoryBean.java:446)
	at org.mybatis.spring.SqlSessionFactoryBean.afterPropertiesSet(SqlSessionFactoryBean.java:408)
	at org.mybatis.spring.SqlSessionFactoryBean.getObject(SqlSessionFactoryBean.java:541)
	at org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration.sqlSessionFactory(MybatisAutoConfiguration.java:150)
	at org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration$$EnhancerBySpringCGLIB$$52afd54c.CGLIB$sqlSessionFactory$1(<generated>)
	at org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration$$EnhancerBySpringCGLIB$$52afd54c$$FastClassBySpringCGLIB$$50d2c770.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration$$EnhancerBySpringCGLIB$$52afd54c.sqlSessionFactory(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45009)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45012)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 22 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:46674', transport: 'socket'

Process finished with exit code 1
```

**Comment by kazuki43zoo** [comment]
Could you provide small reproduce project via GitHub?

**Comment by zhangjiaxin281** [comment]
https://github.com/zhangjiaxin281/rabbitmq-hello.git

**Comment by kazuki43zoo** [comment]
@zhangjiaxin281 I cannot reproduce using your demo application. 

Could you explain how to reproduce this issue using your demo application?

**Comment by zhangjiaxin281** [comment]
Thank you very much for your reply in such a short time!
The 1.3.2 version of mybatis-spring-boot-starter is used in the project, and the program will start normally when starting the project.
Change to version 2.0.0 in gradle, reload the version, and start the project program does not start normally, and an error is reported.

**Comment by zhangjiaxin281** [comment]
Just now, I submitted my project to github and downloaded it. I did not change anything. After the compilation, it was successful.And then I ran it again without success, and then I ran it again without success.To quote NullPointerException error.

**Comment by treezhu** [comment]
I have the same problem.it was successful when I change it to the 1.1.1 version.

**Comment by zhangjiaxin281** [comment]
@kazuki43zoo I want your help. Other people are having this problem.

**Comment by kazuki43zoo** [comment]
I want to help yours ! But I cannot reproduce this...

@treezhu Could your provide small reproduce project via GitHub?

**Comment by iPhotoner** [comment]
@zhangjiaxin281 it works.@see
https://github.com/iPhotoner/demonstration-repository/tree/master/demo-mybatis-spring-boot-starter

**Comment by kazuki43zoo** [comment]
I've closed because no-reply. 
If you cannot resolve this, Please reopen this attached with a small reproduce project via GitHub.

Thanks.

**Comment by Kinhan** [comment]
This bug can be reproduced by starting with jrebel (version:2018.2.6) and Mybatis-spring-boot-starter (version:2.0.0/2.0.1). Use jrebel (version:2018.2.6) and Mybatis-spring-boot-starter (version:1.3.x
) will not appear this bug.

**Comment by kazuki43zoo** [comment]
Hi @Kinhan , I've tried to use with JRebel 2019.1.1(plugins of IntelliJ IDEA). However, I cannot reproduce this. Could you provide reproduce project?

**Comment by kazuki43zoo** [comment]
Hi @Kinhan , If you use the mybatis-spring 2.0.x depend on mybatis-spring-boot-starter 2.0.x on JRebel, you need to use JRebel JRebel 2019.1+. Please see the [release note of JRebel](https://jrebel.com/software/jrebel/download/changelog/2019-x/).

**Comment by kazuki43zoo** [comment]
@zhangjiaxin281 Are you use mybatis-spring-boot-starter on JRebel 2018.2.x or under version?

**Comment by Kinhan** [comment]
Hi @kazuki43zoo, You are right. I could not reproduce the bug after I updated my JRebel 2018.x(plugin of IntelliJ IDEA) to JRebel 2019.1.1(plugin of IntelliJ IDEA). This's my fault, I should read the release note of JRebel first, sorry.

**Comment by zhangjiaxin281** [comment]
@kazuki43zoo I started the project on the lower version before, but now I upgrade to the latest version and this problem does not appear. Thanks again!
