### ISSUE TITLE
Support build using OpenJDK EA on Travis CI

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/spring-boot-starter#351]

**Comment by kazuki43zoo** [comment]
Revert because mybatis-spring-boot-sample-groovy is build error as follow:

```
...
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6.3:generateStubs (default) on project mybatis-spring-boot-sample-groovy: Error occurred while calling a method on a Groovy class from classpath. InvocationTargetException: startup failed:
[ERROR] General error during conversion: Unsupported class file major version 58
[ERROR] 
[ERROR] java.lang.IllegalArgumentException: Unsupported class file major version 58
[ERROR] 	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:195)
[ERROR] 	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:176)
[ERROR] 	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:162)
[ERROR] 	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:283)
[ERROR] 	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
...
```

I've tried using gmavenplus-plugin 1.7.1(latest version), but it cannot fix.

**Comment by kazuki43zoo** [comment]
Probably, this cause is that the Groovy does not support with JDK 14 yet.

**Comment by kazuki43zoo** [comment]
https://issues.apache.org/jira/projects/GROOVY/issues/GROOVY-9177
