### ISSUE TITLE
New release 1.0.1 is crashing

### ISSUE THREAD

**Issue by bostone** [mybatis/spring-boot-starter#36]
Just by switching from 1.0.0 to 1.0.1 (no other code changes) when attempting to run I now get this error:
 
```
Caused by: java.lang.IllegalStateException: Cannot find config location: ServletContext resource [/mybatis-config.xml] (please add config file or check your Mybatis configuration)
        at org.springframework.util.Assert.state(Assert.java:392) ~[spring-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        at org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration.checkConfigFileExists(MybatisAutoConfiguration.java:97) ~[mybatis-spring-boot-autoconfigure-1.0.1.jar:1.0.1]
        at sun.reflect.NahodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]

        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305) ~[spring-beans-4.2.5.RELEASE.jar:4.
2.5.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.
RELEASE]
        ... 51 common frames omitted
```

To reiterate - mybatis-config.xml is there in the jar and the app runs fine with 1.0.0

**Comment by kazuki43zoo** [comment]
Can you provide a repro project in GitHub ?

**Comment by eddumelendez** [comment]
Hi @bostone you may need to use

```
mybatis.config=classpath:mybatis-config.xml
```

**Comment by emacarron** [comment]
No reply.
