### ISSUE TITLE
Fully executable Jar does not scan typeAlias

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/spring-boot-starter#38]
mybatis-spring-boot 1.0.1 does not scan typeAlias from specified package as follow:

```properties
mybatis.type-aliases-package=com.example.model
```

Specify a type alias in Mapper XML

```xml
<!DOCTYPE mapper PUBLIC
        "-//mybatis.org//DTD Mapper 3.0//EN"
        "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.example.mapper.MessageMapper">
    <select id="findOne" resultType="Message"> <!-- ## Use type alias -->
        SELECT code, message FROM t_message WHERE code = #{code}
    </select>
</mapper>
```
Settings for building a fully executable jar

```xml
<build>
    <plugins>
        <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
            <configuration>
                <executable>true</executable> <!-- Add -->
            </configuration>
        </plugin>
    </plugins>
</build>
```

Build a fully executable jar

```console
$ ./mvnw clean install
```

Run a fully executable jar

```console
$ java -jar target/xxxx.jar
...
        at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:118)
        ... 44 more
Caused by: org.apache.ibatis.type.TypeException: Could not resolve type alias 'Message'.  Cause: java.lang.ClassNotFoundException: Cannot find class: Message
        at org.apache.ibatis.type.TypeAliasRegistry.resolveAlias(TypeAliasRegistry.java:120)
        at org.apache.ibatis.builder.BaseBuilder.resolveAlias(BaseBuilder.java:149)
        at org.apache.ibatis.builder.BaseBuilder.resolveClass(BaseBuilder.java:116)
        ... 48 more
...
```

Related issue : #35

**Comment by kazuki43zoo** [comment]
I've added repro project for this.

https://github.com/kazuki43zoo/mybatis-spring-boot-gh-38

**Comment by kazuki43zoo** [comment]
I've confirmed to fix this issue using mybatis-spring 1.2.5-SNAPSHOT.

How to install the mybatis-spring 1.2.5-SNAPSHOT into local repository.
```console
git clone https://github.com/mybatis/spring.git
cd spring
git checkout 1.2.x
mvn install
```

And i changed a version of mybatis-spring.

```
<dependency>
    <groupId>org.mybatis</groupId>
    <artifactId>mybatis-spring</artifactId>
    <version>1.2.5-SNAPSHOT</version>
</dependency>
```

Build a fully executable jar

```
$ ./mvnw clean install
```

Run a fully executable jar

```console
$ java -jar target/xxxx.jar
...
2016-03-29 02:15:06.045  INFO 50107 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-03-29 02:15:06.107  INFO 50107 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2016-03-29 02:15:06.110  INFO 50107 --- [           main] com.example.Application                  : Started Application in 2.711 seconds (JVM running for 3.05)
```

Access to http://localhost:8080/

```
$ curl http://localhost:8080/
Hello!!
```

**Comment by kazuki43zoo** [comment]
This issue will fix via https://github.com/mybatis/spring/pull/121.

**Comment by emacarron** [comment]
Thank you @kazuki43zoo !!

@eddumelendez  @kazuki43zoo  Just let us know if we need a new release of the spring module to fix this.

**Comment by kazuki43zoo** [comment]
@eddumelendez , @eddumelendez 

I think that spring-mybatis 1.2.5 and mybatis-spring-boot 1.0.2 should release as soon as possible.

**Comment by eddumelendez** [comment]
Thanks @kazuki43zoo to report this issue

@emacarron I have tested version 1.2.5-SNAPSHOT and it is working fine. Do you think we can perform a release of mybatis-spring? Thanks in advance.

**Comment by emacarron** [comment]
Of course we can. Let me know if spring-boot is ready for a release and will make both releases asap.

**Comment by emacarron** [comment]
Ah, sorry, I see there are no changes in spring-boot so we only need a release of the spring module. Lets go then.

**Comment by emacarron** [comment]
Finally fixed by upgrading the MyBatis-Spring dependency  with commit 8fe17c4520769b9d74ac8bc47c1db14773da3436

**Comment by gituser786** [comment]
I am using spring boot version 1.5.4 along with spring-mybatis 1.3.0. mybatis-spring-boot-starter 1.3.0
I am getting same error when I execute as a jar file. But in eclipse I don't get any error. Please help to solve this issue --Nizam

**Comment by kazuki43zoo** [comment]
@gituser786 Could you provide a small reproduce project via GitHub repository?

**Comment by TracyBin** [comment]
I encountered the same problem
```
<dependency>
    <groupId>org.mybatis.spring.boot</groupId>
    <artifactId>mybatis-spring-boot-starter</artifactId>
    <version>1.3.1</version>
</dependency>
```

```
Caused by: java.lang.ClassNotFoundException: Cannot find class: UserMobileRlt
	at org.apache.ibatis.io.ClassLoaderWrapper.classForName(ClassLoaderWrapper.java:200) ~[mybatis-3.4.5.jar!/:3.4.5]
	at org.apache.ibatis.io.ClassLoaderWrapper.classForName(ClassLoaderWrapper.java:89) ~[mybatis-3.4.5.jar!/:3.4.5]
	at org.apache.ibatis.io.Resources.classForName(Resources.java:261) ~[mybatis-3.4.5.jar!/:3.4.5]
	at org.apache.ibatis.type.TypeAliasRegistry.resolveAlias(TypeAliasRegistry.java:116) ~[mybatis-3.4.5.jar!/:3.4.5]
	at org.apache.ibatis.builder.BaseBuilder.resolveAlias(BaseBuilder.java:149) ~[mybatis-3.4.5.jar!/:3.4.5]
	at org.apache.ibatis.builder.BaseBuilder.resolveClass(BaseBuilder.java:116) ~[mybatis-3.4.5.jar!/:3.4.5]
	at org.apache.ibatis.builder.xml.XMLStatementBuilder.parseStatementNode(XMLStatementBuilder.java:74) ~[mybatis-3.4.5.jar!/:3.4.5]
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.buildStatementFromContext(XMLMapperBuilder.java:135) ~[mybatis-3.4.5.jar!/:3.4.5]
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.buildStatementFromContext(XMLMapperBuilder.java:128) ~[mybatis-3.4.5.jar!/:3.4.5]
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:118) ~[mybatis-3.4.5.jar!/:3.4.5]
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.parse(XMLMapperBuilder.java:92) ~[mybatis-3.4.5.jar!/:3.4.5]
	at org.mybatis.spring.SqlSessionFactoryBean.buildSqlSessionFactory(SqlSessionFactoryBean.java:521) ~[mybatis-spring-1.3.1.jar!/:1.3.1]
	at org.mybatis.spring.SqlSessionFactoryBean.afterPropertiesSet(SqlSessionFactoryBean.java:380) ~[mybatis-spring-1.3.1.jar!/:1.3.1]
	at org.mybatis.spring.SqlSessionFactoryBean.getObject(SqlSessionFactoryBean.java:547) ~[mybatis-spring-1.3.1.jar!/:1.3.1]
	at com.asiainfo.config.MasterDataSourceConfig.masterSqlSessionFactory(MasterDataSourceConfig.java:66) ~[classes!/:0.0.1]
	at com.asiainfo.config.MasterDataSourceConfig$$EnhancerBySpringCGLIB$$900291c.CGLIB$masterSqlSessionFactory$0(<generated>) ~[classes!/:0.0.1]
	at com.asiainfo.config.MasterDataSourceConfig$$EnhancerBySpringCGLIB$$900291c$$FastClassBySpringCGLIB$$791687e5.invoke(<generated>) ~[classes!/:0.0.1]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at com.asiainfo.config.MasterDataSourceConfig$
```
```
 @Bean(name = "masterSqlSessionFactory")
    @Primary
    public SqlSessionFactory masterSqlSessionFactory(@Qualifier("masterDataSource") DataSource masterDataSource)
            throws Exception {
        final SqlSessionFactoryBean sessionFactory = new SqlSessionFactoryBean();
        sessionFactory.setDataSource(masterDataSource);
        sessionFactory.setMapperLocations(new PathMatchingResourcePatternResolver()
                .getResources(MasterDataSourceConfig.MAPPER_LOCATION));
        sessionFactory.setTypeAliasesPackage(MasterDataSourceConfig.TYPEALIASESPACKAGE);
        return sessionFactory.getObject();
    }
```

**Comment by kazuki43zoo** [comment]
Hi @TracyBin , please set the `SpringBootVFS` to an `SqlSessionFactoryBean` instance as follow:

https://github.com/mybatis/spring-boot-starter/blob/a92ba00d578221acb7dd01ef7a7e5fa25456d467/mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java#L118-L120

**Comment by TracyBin** [comment]
@kazuki43zoo , Yes,the problem is solved.Thanks for your reply.

**Comment by kazuki43zoo** [comment]
Hi @TracyBin , I've added an explanation for this. See 5c77a8e047b643df8c88f20aa5d993d64cc275dd.
Thanks.

**Comment by kazuki43zoo** [comment]
@shreyasGit 
Could you provide a reproduce project on GitHub?

**Comment by shreyasGit** [comment]
Ok does that mean I need to provide a sample spring boot project which
replicates problem ? My application is quite huge, moving from spring 3.1
to boot. I will not be able to provide entire thing

**Comment by kazuki43zoo** [comment]
If you need my help, I want to a **small reproduce project**.
It is difficult to analyze issue with stack trace alone in this case.
