### ISSUE TITLE
Cannot deploy with spring boot 2.2.0.RELEASE because occur BindException

### ISSUE THREAD

**Issue by JangCool** [mybatis/spring-boot-starter#387]
I upgraded from version 2.2.0.M2 of Spring Boot 2 to 2.2.0.RELEASE version.

But.... when I run the server, MyBatis throws a BindException happen.

i deploy war file on tomcat.

What is problem?... I really need help.

Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'mybatis.configuration.result-maps[0]' to org.apache.ibatis.mapping.ResultMap

=============== full exception =========================

```
21-Oct-2019 16:52:29.567 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:976)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1853)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'mybatis-org.mybatis.spring.boot.autoconfigure.MybatisProperties': Could not bind properties to 'MybatisProperties' : prefix=mybatis, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'mybatis.configuration.result-maps[0]' to org.apache.ibatis.mapping.ResultMap
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:787)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:226)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:152)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:132)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:92)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5303)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 10 more
Caused by: org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'mybatis-org.mybatis.spring.boot.autoconfigure.MybatisProperties': Could not bind properties to 'MybatisProperties' : prefix=mybatis, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'mybatis.configuration.result-maps[0]' to org.apache.ibatis.mapping.ResultMap
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:110)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:96)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1795)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:874)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:778)
	... 32 more
Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'mybatis.configuration.result-maps[0]' to org.apache.ibatis.mapping.ResultMap
	at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:337)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:297)
	at org.springframework.boot.context.properties.bind.Binder.lambda$null$1(Binder.java:385)
	at org.springframework.boot.context.properties.bind.Binder$Context.withSource(Binder.java:519)
	at org.springframework.boot.context.properties.bind.Binder$Context.access$1000(Binder.java:486)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$2(Binder.java:386)
	at org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindIndexed(IndexedElementsBinder.java:106)
	at org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindIndexed(IndexedElementsBinder.java:86)
	at org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindIndexed(IndexedElementsBinder.java:71)
	at org.springframework.boot.context.properties.bind.CollectionBinder.bindAggregate(CollectionBinder.java:49)
	at org.springframework.boot.context.properties.bind.AggregateBinder.bind(AggregateBinder.java:56)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$3(Binder.java:388)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:543)
	at org.springframework.boot.context.properties.bind.Binder$Context.access$200(Binder.java:486)
	at org.springframework.boot.context.properties.bind.Binder.bindAggregate(Binder.java:388)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:349)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:293)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$4(Binder.java:421)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:88)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:77)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:54)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:425)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:543)
	at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:529)
	at org.springframework.boot.context.properties.bind.Binder$Context.access$500(Binder.java:486)
	at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:423)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:364)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:293)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$4(Binder.java:421)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:88)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:77)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:54)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:425)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:543)
	at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:529)
	at org.springframework.boot.context.properties.bind.Binder$Context.access$500(Binder.java:486)
	at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:423)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:364)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:293)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:281)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:211)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:198)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bind(ConfigurationPropertiesBinder.java:89)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:107)
	... 46 more
Caused by: java.lang.IllegalStateException: Failed to extract parameter names for org.apache.ibatis.mapping.ResultMap(org.apache.ibatis.mapping.ResultMap$1)
	at org.springframework.util.Assert.state(Assert.java:94)
	at org.springframework.boot.context.properties.bind.ValueObjectBinder$DefaultValueObject.parseConstructorParameters(ValueObjectBinder.java:178)
	at org.springframework.boot.context.properties.bind.ValueObjectBinder$DefaultValueObject.<init>(ValueObjectBinder.java:173)
	at org.springframework.boot.context.properties.bind.ValueObjectBinder$DefaultValueObject.get(ValueObjectBinder.java:218)
	at org.springframework.boot.context.properties.bind.ValueObjectBinder$DefaultValueObject.get(ValueObjectBinder.java:206)
	at org.springframework.boot.context.properties.bind.ValueObjectBinder$ValueObject.get(ValueObjectBinder.java:112)
	at org.springframework.boot.context.properties.bind.ValueObjectBinder.bind(ValueObjectBinder.java:51)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:425)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:543)
	at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:529)
	at org.springframework.boot.context.properties.bind.Binder$Context.access$500(Binder.java:486)
	at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:423)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:364)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:293)
	... 88 more

21-Oct-2019 16:52:29.569 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive /usr/local/tomcat/webapps/ROOT.war
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:757)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:976)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1853)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by kazuki43zoo** [comment]
@JangCool  Could you provide a small reproduce project via GitHub?
I think this issue is same with #350.

**Comment by JangCool** [comment]
@kazuki43zoo 
The error seems to be different. The part that coincides with issue #350 is that it uses 1.2.0.4.0-atlassian-hosted.jar.

AND.... i use mybatis-starter version 2.1.1

		
		<dependency>
		    <groupId>org.mybatis.spring.boot</groupId>
		    <artifactId>mybatis-spring-boot-starter</artifactId>
			<version>2.1.1</version>		    
		</dependency>

**Comment by kazuki43zoo** [comment]
OK. But I cannot reproduce. Please provide a reproduce project.

**Comment by JangCool** [comment]
@kazuki43zoo 

I'm sorry, but the current project is a joint project and we can't sample it.

**Comment by kazuki43zoo** [comment]
@JangCool I can reproduce this issue. I will investigate this as soon as possible. Thanks for your report!

**Comment by JangCool** [comment]
@kazuki43zoo OK, thank you , i'll wait for you.

**Comment by kazuki43zoo** [comment]
@JangCool If you does not use JNDI feature on your application, probably you can prevent this error by https://github.com/mybatis/spring-boot-starter/issues/350#issuecomment-500480499 as workaround.

**Comment by JangCool** [comment]
@kazuki43zoo 

Yes, I did not use jndi. I tried it.

**Comment by JangCool** [comment]
@kazuki43zoo 
It's possible!!!! Thank you very much.

**Comment by kazuki43zoo** [comment]
I've created a new issue on spring-boot. See spring-projects/spring-boot#18670.

**Comment by kazuki43zoo** [comment]
@JangCool This issue will resolve by upgrading to spring-boot 2.2.1.RELEASE (no need upgrading mybatis-spring-boot-starter). Please drop workaround and checking!! Thanks!
