### ISSUE TITLE
Build error on openjdk-ea(openjdk15)

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/spring-boot-starter#409]
https://travis-ci.org/mybatis/spring-boot-starter/jobs/626444557

- [x] Apply workaround via gh-410
- [x] Support JKD 15 on Groovy ([Issue on Groovy](https://issues.apache.org/jira/browse/GROOVY-9349))

**Comment by kazuki43zoo** [comment]
Groovy does not support jdk15 yet.

```
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.8.1:generateStubs (default) on project mybatis-spring-boot-sample-groovy: Error occurred while calling a method on a Groovy class from classpath. InvocationTargetException: startup failed:
[ERROR] General error during conversion: Unsupported class file major version 59
[ERROR] 
[ERROR] java.lang.IllegalArgumentException: Unsupported class file major version 59
[ERROR] 	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:195)
[ERROR] 	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:176)
[ERROR] 	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:162)
[ERROR] 	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:283)
[ERROR] 	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
[ERROR] 	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
[ERROR] 	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
[ERROR] 	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
...
```
