### ISSUE TITLE
Deadlock Retry

### ISSUE THREAD

**Issue by neodem** [mybatis/spring-boot-starter#474]
I'm using the mybatis-spring-boot-starter (2.0.1) and I'm having an issue where sometimes I get a deadlock writing to mysql:

> com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:123)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:637)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	at jdk.internal.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)

This is transient and I think it happens with load and I also think it is normal and can be solved with a simple retry. 

However, I'm not sure where/how to implement the retry. I know spring supports AOP and also the @Retry annotation, etc. but since the s-b-s makes things so easy, I only declare a datasource in my config and a bunch of @Mapper interfaces and s-b-s takes care of everything else.

I'm curious if the s-b-s has a simple way to add/enable retry on failed deadlock exceptions.

**Comment by kazuki43zoo** [comment]
Hi @neodem , 

The mybatis-spring-boot(mybatis core and mybatis-spring) no provide a retry feature.
If you need retry feature, probably you can use the spring-retry(`@Retry`) at mapper interface (interface that annotated `@Mapper`).

**Comment by kazuki43zoo** [comment]
Close this issue because no reaction.
