### ISSUE TITLE
Issue with MyBatis+Derby embedded database in Springboot :ERROR 42X05:

### ISSUE THREAD

**Issue by gayatrigithub-java** [mybatis/spring-boot-starter#809]
Hi All,

I am trying to migrate the Spring project with MyBatis+Derby embedded database to Springboot. 
Spring boot version -2.7.3
mybatis -3.5.6
mybatis-spring- 2.1.0
org.mybatis.spring.boot - mybatis-spring-boot-starter -2.3.0
java version - 11.0.17

1. I have created datasource bean in java-config file in spring boot  which was in applicationContext.xml in the spring project. In spring boot namespace "  xmlns:mybatis="http://mybatis.org/schema/mybatis-spring" was not supported so xml configuration is not working in SpringBoot.

below are my data source bean

```java
@PostConstruct
	@Bean(name = "sqlSessionFactory")
	public SqlSessionFactoryBean sqlSessionFactory() throws Exception {
		SqlSessionFactoryBean sqlSessionFactory = new SqlSessionFactoryBean();
		try {
			sqlSessionFactory.setDataSource(dataSource());
			sqlSessionFactory.setConfigLocation(sqlMapConfigResources());
			sqlSessionFactory.setVfs(SpringBootVFS.class);
			} catch (Exception e) {
			e.printStackTrace();
		}
		return sqlSessionFactory;
	}


@Bean(name = "dataSource")
	public BasicDataSource dataSource() throws InstantiationException, IllegalAccessException, ClassNotFoundException {
		BasicDataSource dataSource = new BasicDataSource();
		dataSource.setDriverClassName("org.apache.derby.jdbc.EmbeddedDriver");
		dataSource.setUrl("jdbc:derby:db/runtime/ClientDB;create=true");
		dataSource.setDefaultAutoCommit(true);
		dataSource.setMaxTotal(25);
		dataSource.setMaxIdle(5);
		dataSource.setDefaultQueryTimeout(60);
		return dataSource;
	}

	private static Resource sqlMapConfigResources() throws Exception {
		return new PathMatchingResourcePatternResolver().getResource("classpath:sql-map-config.xml");

	}
```

3.  **sql-map-config.xml**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration
        PUBLIC "-//mybatis.org//DTD Config 3.0//EN"
        "Http://mybatis.org/dtd/mybatis-3-config.dtd">

<configuration>
	 <settings>
        <setting name="lazyLoadingEnabled" value="true"/>
        <setting name="mapUnderscoreToCamelCase" value="false"/>
    </settings>
    <typeAliases>
        <typeAlias alias="parameter" type="cz.wincor_nixdorf.esf.db.entities.ParameterEntity" />
        <typeAlias alias="fileMetadata" type="db.entities.FileMetadataEntity" />
        <typeAlias alias="action" type="db.entities.ActionEntity" />
        <typeAlias alias="actionParameter" type="db.entities.ActionParameterEntity" />
        <typeAlias alias="list" type="java.util.List" />
        <typeAlias alias="iceEvent" type="pojos.monitoring.IceEvent" />
        <typeAlias alias="serverMessage" type="db.entities.ServerMessageEntity" />
        <typeAlias alias="position" type="db.entities.PositionEntity" />
        <typeAlias alias="swdDepotEntity" type="db.entities.SWDDepotEntity" />
        <typeAlias alias="swdPackage" type="db.entities.SWDPackageEntity" />
        <typeAlias alias="swdPackageOption" type="db.entities.SWDPackageOptionEntity" />
        <typeAlias alias="swdDepotClient" type="pojos.swd.SWDDepotClient" />
        <typeAlias alias="swdRecorder" type="db.entities.SWDRecorderEntity" />
        <typeAlias alias="update" type="db.entities.UpdateEntity" />
        <typeAlias alias="position" type="db.entities.PositionEntity" />
        <typeAlias alias="invScan" type="db.entities.InventoryScanEntity" />
        <typeAlias alias="clientTransferEvent" type="events.reconnect.dms.ClientTransferEvent" />
    </typeAliases>

    <environments default="testing">
        <environment id="testing">
            <transactionManager type="JDBC">
                <property name="" value="" />
            </transactionManager>
            <dataSource type="UNPOOLED">
                <property name="driver" value="org.apache.derby.jdbc.EmbeddedDriver" />
                <property name="url" value="jdbc:derby:memory:mybatis;create=true" />
            </dataSource>
        </environment>
    </environments>

    <mappers>
        <mapper resource="ibatis/Parameters.xml" />
        <mapper resource="ibatis/FileMetadata.xml" />
        <mapper resource="ibatis/Actions.xml" />
        <mapper resource="ibatis/EventPersistance.xml" />
        <mapper resource="ibatis/ServerMessages.xml" />
        <mapper resource="ibatis/Positions.xml" />
        <mapper resource="ibatis/SWDDepot.xml" />
        <mapper resource="ibatis/SWDPackages.xml" />
        <mapper resource="ibatis/SWDRecorders.xml" />
        <mapper resource="ibatis/Updates.xml" />
        <mapper resource="ibatis/InvScans.xml" />
        <mapper resource="ibatis/ClientTransferEvents.xml" />
    </mappers>
</configuration>
```

4. Added @Mapper annotation to all the Mapper classes 

But getting below error 

```
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table/View 'PARAMETERS' does not exist.
### The error may exist in db/dao/ParametersDAO.java (best guess)
### The error may involve db.dao.ParametersDAO.getParameter
### The error occurred while executing a query
### SQL: SELECT value FROM parameters WHERE name = ?
### Cause: java.sql.SQLSyntaxErrorException: Table/View 'PARAMETERS' does not exist.
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table/View 'PARAMETERS' does not exist.
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'executeStoredActionJob' defined in file [C:\Workspace\ESF\esfclient\target\classes\esf\jobs\ExecuteStoredActionJob.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'actionManager': Unsatisfied dependency expressed through method 'setInitializationManager' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initializationManager': Invocation of init method failed; nested exception is org.springframework.jdbc.BadSqlGrammarException:
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table/View 'PARAMETERS' does not exist.
### The error may exist in db/dao/ParametersDAO.java (best guess)
### The error may involve db.dao.ParametersDAO.getParameter
### The error occurred while executing a query
### SQL: SELECT value FROM parameters WHERE name = ?
### Cause: java.sql.SQLSyntaxErrorException: Table/View 'PARAMETERS' does not exist.
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table/View 'PARAMETERS' does not exist.
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
        at ServiceLauncher.main(ServiceLauncher.java:53)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'actionManager': Unsatisfied dependency expressed through method 'setInitializationManager' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initializationManager': Invocation of init method failed; nested exception is org.springframework.jdbc.BadSqlGrammarException:
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table/View 'PARAMETERS' does not exist.
### The error may exist in db/dao/ParametersDAO.java (best guess)
### The error may involve db.dao.ParametersDAO.getParameter
### The error occurred while executing a query
### SQL: SELECT value FROM parameters WHERE name = ?
### Cause: java.sql.SQLSyntaxErrorException: Table/View 'PARAMETERS' does not exist.
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table/View 'PARAMETERS' does not exist.
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.resolveMethodArguments(AutowiredAnnotationBeanPostProcessor.java:767)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:719)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
        ... 16 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initializationManager': Invocation of init method failed; nested exception is org.springframework.jdbc.BadSqlGrammarException:
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table/View 'PARAMETERS' does not exist.
### The error may exist in db/dao/ParametersDAO.java (best guess)
### The error may involve db.dao.ParametersDAO.getParameter
### The error occurred while executing a query
### SQL: SELECT value FROM parameters WHERE name = ?
### Cause: java.sql.SQLSyntaxErrorException: Table/View 'PARAMETERS' does not exist.
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table/View 'PARAMETERS' does not exist.
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.resolveMethodArguments(AutowiredAnnotationBeanPostProcessor.java:759)
        ... 31 more
Caused by: org.springframework.jdbc.BadSqlGrammarException:
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table/View 'PARAMETERS' does not exist.
### The error may exist in db/dao/ParametersDAO.java (best guess)
### The error may involve db.dao.ParametersDAO.getParameter
### The error occurred while executing a query
### SQL: SELECT value FROM parameters WHERE name = ?
### Cause: java.sql.SQLSyntaxErrorException: Table/View 'PARAMETERS' does not exist.
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table/View 'PARAMETERS' does not exist.
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:439)
        at com.sun.proxy.$Proxy82.selectOne(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:160)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87)
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)
        at com.sun.proxy.$Proxy86.getParameter(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy78.getParameter(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
        at com.sun.proxy.$Proxy78.getParameter(Unknown Source)
        at managers.impl.ParametersDbManagerImpl.getParameter(ParametersDbManagerImpl.java:33)
        at managers.impl.ParametersDbManagerImpl.storeParameter(ParametersDbManagerImpl.java:38)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
        at com.sun.proxy.$Proxy77.storeParameter(Unknown Source)
        at managers.impl.InitializationManagerImpl.setup(InitializationManagerImpl.java:143)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
        ... 43 more
Caused by: java.sql.SQLSyntaxErrorException: Table/View 'PARAMETERS' does not exist.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
        at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
        at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:292)
        at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:292)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:86)
        at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
        at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:87)
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
        ... 84 more
Caused by: ERROR 42X05: Table/View 'PARAMETERS' does not exist.
        at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
        at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromBaseTable.bindTableDescriptor(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromBaseTable.bindNonVTITables(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromList.bindTables(Unknown Source)
        at org.apache.derby.impl.sql.compile.SelectNode.bindNonVTITables(Unknown Source)
        at org.apache.derby.impl.sql.compile.DMLStatementNode.bindTables(Unknown Source)
        at org.apache.derby.impl.sql.compile.DMLStatementNode.bind(Unknown Source)
        at org.apache.derby.impl.sql.compile.CursorNode.bindStatement(Unknown Source)
        at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
        at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
        at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
        ... 108 more
```

any configuration missing ??? ...Any Help will be appreciated.

**Comment by kazuki43zoo** [comment]
@gayatrigithub-java Please tell me how to create the `parameters` table on above application. And ... Could you provide a repro project?

**Comment by kazuki43zoo** [comment]
@gayatrigithub-java  
I close this issue because no reply, you can always reopen.
