### ISSUE TITLE
The latest springboot using mybatis-spring-stater 3.0.2 throw exception "Invalid value type for attribute 'factoryBeanObjectType': java.lang.String"

### ISSUE THREAD

**Issue by aalx** [mybatis/spring-boot-starter#881]
Springboot Version 3.2.0-M2,spring-boot-starter 3.0.2
In this version ,FactoryBeanRegistrySupport.getTypeForFactoryBeanFromAttributes() method has been changed,throw a IllegalArgumentException when "factoryBeanObjectType" not ResolvableType、Class type。But in ClassPathMapperScanner.processBeanDefinitions() menthod (  line 277) set a String type with beanClassName,

**Comment by Iscrdr** [comment]
I also encountered the same problem.
springboot.version 3.2.0-SNAPSHOT  and    mybatis-spring-boot-starter 3.0.2(3.0.0)

error:

java.lang.IllegalArgumentException: Invalid value type for attribute 'factoryBeanObjectType': java.lang.String
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getTypeForFactoryBeanFromAttributes(FactoryBeanRegistrySupport.java:86) ~[spring-beans-6.1.0-20231005.151344-685.jar:6.1.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:838) ~[spring-beans-6.1.0-20231005.151344-685.jar:6.1.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:620) ~[spring-beans-6.1.0-20231005.151344-685.jar:6.1.0-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:573) ~[spring-beans-6.1.0-20231005.151344-685.jar:6.1.0-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:532) ~[spring-beans-6.1.0-20231005.151344-685.jar:6.1.0-SNAPSHOT]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:136) ~[spring-context-6.1.0-20231005.151344-685.jar:6.1.0-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:768) ~[spring-context-6.1.0-20231005.151344-685.jar:6.1.0-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:589) ~[spring-context-6.1.0-20231005.151344-685.jar:6.1.0-SNAPSHOT]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.0-20231005.140510-385.jar:3.2.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) ~[spring-boot-3.2.0-20231005.140510-385.jar:3.2.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) ~[spring-boot-3.2.0-20231005.140510-385.jar:3.2.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-3.2.0-20231005.140510-385.jar:3.2.0-SNAPSHOT]

**Comment by techwn** [comment]
I got the same error, but this is closed as completed, why? any pr about this?

**Comment by kazuki43zoo** [comment]
@Iscrdr @techwn Please try the [mybatis-spring-boot 3.0.3-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/mybatis/spring/boot/mybatis-spring-boot/3.0.3-SNAPSHOT/). See #896.
