### ISSUE TITLE
NoSuchBeanDefinitionException:SqlSession

### ISSUE THREAD

**Issue by qinxi** [mybatis/spring-boot-starter#92]
when I upgrade to gradle 3.0 ,spring boot 1.4 ,mybatis-spring-boot1.1.1 

```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.apache.ibatis.session.SqlSession] found for dependency [org.apache.ibatis.session.SqlSession]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.annotation.Resource(shareable=true, lookup=, name=, description=, authenticationType=CONTAINER, type=class java.lang.Object, mappedName=)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1406)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1057)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1019)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:518)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:496)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:627)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:169)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:318)
	... 22 common frames omitted
```

UserRepository.java
```
@Repository
public class UserDao {

    @Resource
    private SqlSession sqlSession;


    public AdminUser search(String name){
        ........
    }
}

```

dependencies
```
dependencies {
    compile("org.springframework.boot:spring-boot-starter-web") {
        exclude module: "spring-boot-starter-tomcat"
    }
    compile("org.springframework.boot:spring-boot-starter-jetty")
    compile("org.springframework.boot:spring-boot-starter-actuator")
    compile("org.mybatis.spring.boot:mybatis-spring-boot-starter:1.1.1")
    compile("org.springframework.boot:spring-boot-starter-jdbc")
    compile ("com.alibaba:druid:1.0.19")
    compile group: 'org.projectlombok', name: 'lombok', version: lombokVersion
    compile("mysql:mysql-connector-java")
}
```
gradle.properties:
```
springBootVersion=1.4.0.RELEASE
spring.version=4.3.2.RELEASE

lombokVersion=1.16.8

```

**Comment by kazuki43zoo** [comment]
Can you provide a repro project on github ?

**Comment by qinxi** [comment]
Hi here  https://github.com/qinxi/gradle3

**Comment by kazuki43zoo** [comment]
Hi @qinxi.

### Root cause

The bean of `DataSource` has not been registered to the DI container.

### Why ?

The auto configure mechanism for datasource has been changed at Spring Boot 1.4.

* http://docs.spring.io/spring-boot/docs/1.4.0.RELEASE/reference/htmlsingle/#boot-features-connect-to-production-database

For details, please refer the source code of `DataSourceAutoConfiguration`.

Probably, Spring Boot 1.4 does not support the auto configure for `DruidDataSource`.
If you use the `DruidDataSource`, please define a bean using `@Bean` method on your `@Configuration` class or change to use the `DataSource` class provided by Tomcat JDBC.

Thanks.

**Comment by zhxxcq** [comment]
This is my configuration example:
`@Configuration
@EnableConfigurationProperties(DataSourceProperties.class)
public class DruidDatasourceConfig {

    @Bean
    @ConfigurationProperties("spring.datasource.druid")
    public DruidDataSource dataSource(
            DataSourceProperties properties) {
        DruidDataSource dataSource = new DruidDataSource();
        dataSource.setDriverClassName(properties.determineDriverClassName());
        dataSource.setUrl(properties.determineUrl());
        dataSource.setUsername(properties.determineUsername());
        dataSource.setPassword(properties.determinePassword());
        DatabaseDriver databaseDriver = DatabaseDriver
                .fromJdbcUrl(properties.determineUrl());
        String validationQuery = databaseDriver.getValidationQuery();
        if (validationQuery != null) {
            dataSource.setTestOnBorrow(true);
            dataSource.setValidationQuery(validationQuery);
        }
        return dataSource;
    }

}`
and yml configuration
spring:
 datasource:
    url: jdbc:mysql://localhost:3306/datasource?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    name: name_app
    username: name_app
    password: password
    druid:
     filters: stat
     maxActive: 20
     initialSize: 1
     maxWait: 60000
     minIdle: 1
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxOpenPreparedStatements: 20

this may be help you, and my program is ok.

**Comment by qinxi** [comment]
that is ok. very nice .

thx.
