### ISSUE TITLE
In Spring Boot 3.2.5 and mybatis-plus-boot-starter 3.5.6, the system encounters an error during initialization :   Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required

### ISSUE THREAD

**Issue by JonyBangBang** [mybatis/spring-boot-starter#970]
Caused by: java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
	at org.springframework.util.Assert.notNull(Assert.java:172) ~[spring-core-6.1.6.jar:6.1.6]
	at org.mybatis.spring.support.SqlSessionDaoSupport.checkDaoConfig(SqlSessionDaoSupport.java:125) ~[mybatis-spring-3.0.3.jar:3.0.3]
	at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:73) ~[mybatis-spring-3.0.3.jar:3.0.3]
	at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44) ~[spring-tx-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1833) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-6.1.6.jar:6.1.6]
	...

**Comment by JonyBangBang** [comment]
把版本降到 spring boot 3.2.3 和 mybatis-plus-boot-starter.version 3.5.5 可以解决上述报错

**Comment by JonyBangBang** [comment]
问题是 spring boot 3.2.5 搭配 mybatis-plus-boot-starter 3.5.6  为什么没有自动装配  sqlSessionFactory？？？

**Comment by VampireAchao** [comment]
？

**Comment by harawata** [comment]
Hello @JonyBangBang ,

mybatis-plus is not our product.
Please report the issue to their tracker.
https://github.com/baomidou/mybatis-plus
